name: Build AnarhoCastleGuard

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload JAR
      uses: actions/upload-artifact@v3
      with:
        name: AnarhoCastleGuard
        path: target/AnarhoCastleGuard-1.0-SNAPSHOT.jar
